name: Build API and push to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: |
          cd api
          mvn clean install
      - uses: actions/upload-artifact@v2
        with:
          name: api-jar
          path: api/target/api-0.0.1-SNAPSHOT.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v2
        with:
          name: api-jar
          path: api/target

      - name: List contents of the api directory
        run: ls -l api

      - name: List contents of the target directory
        run: ls -l api/target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tonci123/devops-java-api:latest