name: Build API and push to Docker Hub

on:
  push:
    branches: ['main']
#    paths: ['api/**']

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar_version: ${{ steps.jar_version.outputs.jar_version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Unit tests
        run: |
          cd api
          mvn test
      - name: Set Build Version
        id: jar_version
        run: |
          cd api
          echo "jar_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
#      - name: Get Build Version
#        env:
#          JAR_VERSION: ${{ steps.jar_version.outputs.jar_version }}
#        run: echo "Jar version - $jar_version"
      - name: Build with Maven
        run: |
          cd api
          mvn clean install
          mv target/api-${{ steps.jar_version.outputs.jar_version }}.jar target/app.jar
      - uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: api/target/app.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: api-jar
          path: api/target
      - name: Get Build Version
        env:
          JAR_VERSION: ${{ needs.build.outputs.jar_version }}
        run: echo "Jar version - $JAR_VERSION"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tonci123/devops-java-api:v${{ needs.build.outputs.jar_version }}
            tonci123/devops-java-api:latest